import{catalog,loadGame}from'./shared/catalog.js';import{createRemoteInputBuffer}from'./shared/input-buffer.js';import{empty,controlMarkup,bindTouch}from'./shared/controls.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),id=params.get('game')||'jelly',info=catalog.find(g=>g.id===id),canvas=$('game-canvas'),ctx=canvas.getContext('2d');
let module,game,phase='loading',mode='solo',keys=new Set(),touch=[empty(),empty()],previous=[empty(),empty()],room=null,stream=null,remote=createRemoteInputBuffer(),remoteAt=[0,0],audio=null,soundEnabled=false,lastSound=0;
function sound(type){if(!soundEnabled||!audio||audio.state!=='running'||performance.now()-lastSound<45)return;lastSound=performance.now();const o=audio.createOscillator(),g=audio.createGain();o.type=/hit|crash|explode/.test(type)?'triangle':'sine';o.frequency.setValueAtTime(/goal|score|collect|win/.test(type)?740:260,audio.currentTime);o.frequency.exponentialRampToValueAtTime(110,audio.currentTime+.12);g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.14);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.15)}
function clearInputs(){keys.clear();touch=[empty(),empty()];previous=[empty(),empty()];remote.clear();remoteAt=[0,0]}
function showOverlay(title,text,button){$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('start').textContent=button;$('overlay').hidden=false}
function completed(result){phase='ended';clearInputs();$('pause').disabled=true;const text=typeof result==='string'?result:result?.text;showOverlay('这一局，尽兴了',text||game?.getState().result||'换个策略，再来一局。','再来一局')}
function reset(auto=false){if(!module)return;phase='ready';clearInputs();game=module.createGame({width:960,height:600,seed:2026,sound,end:completed});$('pause').disabled=true;$('pause').textContent='暂停';const label=mode==='solo'?'你控制 P1，P2 由规则机器人陪玩。':mode==='local'?'两位玩家各自控制角色，也可以用手机加入。':'双方由规则机器人自动演示，可随时切回试玩。';showOverlay(info.title,label,'开始游戏');render();if(auto)start()}
function start(){if(phase==='ended')reset(false);if(!game)return;phase='running';$('overlay').hidden=true;$('pause').disabled=false;$('pause').textContent='暂停';last=performance.now();accum=0;if(audio)safeResume()}
function safeResume(){audio.resume().catch(()=>{})}
function pause(){if(phase==='running'){phase='paused';clearInputs();$('pause').textContent='继续';showOverlay('歇一下，再继续','时间已暂停。点击继续，回到刚才的战局。','继续游戏')}else if(phase==='paused')start()}
function keyboard(i){const sets=i===0?['KeyA','KeyD','KeyW','KeyS','KeyF','KeyG']:['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyK','KeyL'];return{x:Number(keys.has(sets[1]))-Number(keys.has(sets[0])),y:Number(keys.has(sets[3]))-Number(keys.has(sets[2])),action:keys.has(sets[4]),alt:keys.has(sets[5])}}
function inputs(){return[0,1].map(i=>{
  let a,localAction=false,localAlt=false;
  if(mode==='demo'||mode==='solo'&&i===1){a={...empty(),...game.bot(i)};a.pressed=!!a.action&&!previous[i].action;a.altPressed=!!a.alt&&!previous[i].alt;}
  else{
    const k=keyboard(i),t=touch[i];if(performance.now()-remoteAt[i]>=900)remote.clear(i);
    const r=remote.consume(i);localAction=k.action||t.action;localAlt=k.alt||t.alt;
    a={x:Math.max(-1,Math.min(1,k.x+t.x+r.x)),y:Math.max(-1,Math.min(1,k.y+t.y+r.y)),action:localAction||r.action,alt:localAlt||r.alt,
      pressed:localAction&&!previous[i].localAction||r.pressed,altPressed:localAlt&&!previous[i].localAlt||r.altPressed};
  }
  previous[i]={...a,localAction,localAlt};return a;
})}

function update(dt){if(phase!=='running'||!game)return;game.update(dt,inputs());if(game.getState().ended&&phase==='running')completed(game.getState().result)}
function render(){if(!game)return;game.draw(ctx);const s=game.getState();for(let i=0;i<2;i++){$('name'+i).textContent=s.players?.[i]?.name||'P'+(i+1);$('score'+i).textContent=s.players?.[i]?.score??0;$('detail'+i).textContent=s.players?.[i]?.detail||''}$('timer').textContent=String(Math.max(0,Math.ceil(s.timeLeft||0))).padStart(2,'0');$('mode-label').textContent=mode==='solo'?'单人陪练':mode==='local'?'同屏双人':'机器人展示';$('game-status').textContent=s.status||''}
let last=performance.now(),accum=0;function loop(now){accum+=Math.min((now-last)/1000,.1);last=now;if(phase==='running'){while(accum>=1/60){update(1/60);accum-=1/60}}else accum=0;render();requestAnimationFrame(loop)}
const allKeys=new Set(['KeyW','KeyA','KeyS','KeyD','KeyF','KeyG','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','KeyK','KeyL']);addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName))return;if(allKeys.has(e.code)){e.preventDefault();keys.add(e.code)}if(e.code==='Escape'&&(phase==='running'||phase==='paused'))pause()});addEventListener('keyup',e=>{keys.delete(e.code);if(allKeys.has(e.code))e.preventDefault()});addEventListener('blur',()=>{clearInputs();if(phase==='running'&&mode!=='demo')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();if(phase==='running')pause()}});
$('start').onclick=start;$('pause').onclick=pause;$('reset').onclick=()=>reset(false);$('mode').onchange=()=>{mode=$('mode').value;reset(false)};$('sound').onclick=()=>{if(!audio)audio=new AudioContext();safeResume();soundEnabled=!soundEnabled;$('sound').textContent='声音：'+(soundEnabled?'开':'关');$('sound').setAttribute('aria-pressed',soundEnabled);if(soundEnabled)sound('score')};$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('stage').requestFullscreen()}catch{$('game-status').textContent='此浏览器暂不支持全屏，可放大窗口继续玩。'}};
$('touch-zone').innerHTML=controlMarkup(0,'P1 · WASD / F / G')+controlMarkup(1,'P2 · 方向键 / K / L');bindTouch($('touch-zone'),v=>touch=v);
async function post(route,body){const r=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)throw Error(j.error||'连接失败');return j}
function roster(players){$('room-players').replaceChildren();for(let i=0;i<2;i++){const div=document.createElement('div');div.className='room-player';const p=players.find(p=>p.slot===i);div.textContent=`P${i+1} · ${p?'手机已连接':'键盘可用 / 等待手机'}`;$('room-players').append(div);if(!p){remote.clear(i);remoteAt[i]=0}}}
async function closeRoom(){if(stream)stream.close();if(room)try{await post('close',{code:room.code,host:room.host})}catch{}room=null;remote.clear();remoteAt=[0,0];$('room-info').hidden=true;$('create-room').disabled=false;$('mode').disabled=false;$('room-status').textContent='房间已关闭。仍可继续同屏双人游戏。'}
$('create-room').onclick=async()=>{try{$('create-room').disabled=true;const r=await post('create',{game:id});room=r;mode='local';$('mode').value='local';$('mode').disabled=true;reset(false);$('room-code').textContent=r.code;const base=r.urls[0]||location.origin,link=base+'/controller.html?room='+r.code;$('room-link').href=link;$('room-link').textContent=link;$('room-info').hidden=false;$('room-status').textContent='手机连同一 Wi-Fi 后打开此链接。若系统拦截入站连接，可先用同屏键盘玩。';roster([]);stream=new EventSource(`/api/events?code=${r.code}&host=${r.host}`);stream.onmessage=e=>{let v;try{v=JSON.parse(e.data)}catch{return}if(v.type==='input'){remote.receive(v.slot,v.input,phase==='running');remoteAt[v.slot]=performance.now()}if(v.type==='roster')roster(v.players);if(v.type==='closed')closeRoom()};stream.onerror=()=>{$('room-status').textContent='房间连接暂时中断，正在尝试重连。';remote.clear();remoteAt=[0,0]}}catch(e){$('room-status').textContent=e.message;$('create-room').disabled=false}};
$('copy-room').onclick=async()=>{try{await navigator.clipboard.writeText($('room-link').href);$('copy-room').textContent='链接已复制'}catch{$('room-status').textContent='请长按或选中上方链接复制。'}};$('close-room').onclick=closeRoom;addEventListener('pagehide',()=>{if(room)navigator.sendBeacon('/api/close',new Blob([JSON.stringify({code:room.code,host:room.host})],{type:'application/json'}))});
try{if(!info)throw Error('这个游戏不存在，请返回大厅选择。');module=await loadGame(id);document.title=info.title+' · 街机口袋';$('game-title').textContent=info.title;$('game-subtitle').textContent=module.meta.subtitle||info.desc;$('game-number').textContent='0'+(catalog.indexOf(info)+1)+' / 06';for(const text of module.meta.rules){const li=document.createElement('li');li.textContent=text;$('rules').append(li)}$('action-guide').textContent=`F / K / A：${module.meta.actionLabel||'主要动作'}`;$('alt-guide').textContent=`G / L / B：${module.meta.altLabel||'辅助动作'}`;if(params.get('demo')==='1'){mode='demo';$('mode').value='demo'}reset(params.get('demo')==='1');requestAnimationFrame(loop)}catch(e){showOverlay('暂时未能开局',e.message,'返回大厅');$('start').onclick=()=>location.href='/';console.error(e)}
window.arcade={get state(){return{phase,mode,id,game:game?.getState(),room:room?.code||null}},get engine(){return game},start,reset,step(seconds){if(!game)return;for(let n=0;n<Math.floor(seconds*60);n++)update(1/60);render()}};
