import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../games/bubble.js';
const n={x:0,y:0,action:false,alt:false,pressed:false,altPressed:false};
const tick=(g,num,ins=[n,n])=>{for(let f=0;f<num;f++)g.update(1/30,ins);};
test('movement respects walls; two independent players; spawn escape corridors are clear',()=>{for(let seed=0;seed<40;seed++){const g=createGame({seed,testMode:true});const s=g.getState();for(let x=1;x<10;x++)assert.equal(s.board[1][x],0);for(let y=1;y<8;y++)assert.equal(s.board[y][9],0);g.__test.skipReady();tick(g,5,[{...n,x:-1},n]);assert.equal(g.getState().players[0].x,1);g.update(1/30,[{...n,x:1},{...n,y:-1}]);assert.equal(g.getState().players[0].x,2);assert.equal(g.getState().players[1].y,6);}});
test('placing bubble consumes capacity, lets owner leave, but blocks reentry',()=>{const g=createGame({testMode:true});g.__test.skipReady();g.update(1/30,[{...n,pressed:true},n]);assert.equal(g.getState().bombs.length,1);g.update(1/30,[{...n,x:1},n]);tick(g,5);g.update(1/30,[{...n,x:-1,pressed:true},n]);assert.equal(g.getState().players[0].x,2);assert.equal(g.getState().bombs.length,1);});
test('cross blast stops at crates and walls, gives real crate points and chain detonates',()=>{const g=createGame({testMode:true});g.__test.skipReady();g.__test.setPlayer(0,{x:1,y:7});g.__test.setPlayer(1,{x:9,y:7});for(let x=1;x<10;x++)g.__test.setCell(x,3,0);g.__test.setCell(5,3,2);g.__test.setCell(6,3,2);g.__test.addBomb({x:3,y:3,range:4,fuse:.01});g.__test.addBomb({x:2,y:3,range:1,fuse:2});g.update(1/30,[n,n]);const s=g.getState();assert.equal(s.bombs.length,0);assert.equal(s.board[3][5],0);assert.equal(s.board[3][6],2);assert.ok(s.players[0].score>=4);assert.ok(!s.flames.some(f=>f.x===6&&f.y===3));assert.ok(!s.flames.some(f=>s.board[f.y][f.x]===1));});
test('blast round scoring, simultaneous deaths, shield, and item upgrades',()=>{const a=createGame({testMode:true});a.__test.skipReady();a.__test.addBomb({x:1,y:1,fuse:.01});a.update(1/30,[n,n]);assert.equal(a.getState().players[1].score,40);assert.ok(a.getState().players[0].dead);const b=createGame({testMode:true});b.__test.skipReady();b.__test.addBomb({x:1,y:1,fuse:.01});b.update(1/30,[{...n,altPressed:true},n]);assert.equal(b.getState().players[0].dead,false);assert.ok(b.getState().players[0].shield>0);const c=createGame({testMode:true});c.__test.skipReady();c.__test.addBomb({x:1,y:1,fuse:.01});c.__test.addBomb({x:9,y:7,fuse:.01});c.update(1/30,[n,n]);assert.deepEqual(c.getState().players.map(p=>p.wins),[0,0]);const d=createGame({testMode:true});d.__test.skipReady();d.__test.addItem({x:2,y:1,type:'range'});d.update(1/30,[{...n,x:1},n]);assert.equal(d.getState().players[0].range,3);assert.equal(d.getState().players[0].score,3);});
test('bots place and escape bubbles, deterministic games terminate, end fires once and freezes',()=>{function run(){let ends=0,placed=0;const g=createGame({seed:2026,end:()=>ends++});let old=[false,false];for(let f=0;f<2300;f++){const ins=[0,1].map(i=>{const v=g.bot(i);v.pressed=v.action&&!old[i];old[i]=v.action;return v;});g.update(1/30,ins);placed=Math.max(placed,g.getState().bombs.length);}assert.ok(placed>0);assert.equal(ends,1);assert.ok(g.getState().ended);assert.ok(g.getState().players.some(p=>p.score>0));const s=g.getState();tick(g,60);assert.deepEqual(g.getState(),s);return s;}assert.deepEqual(run(),run());});

test("players cannot hide in the same tile or walk through each other",()=>{const g=createGame({testMode:true});g.__test.skipReady();g.__test.setPlayer(1,{x:3,y:1});g.update(1/30,[{...n,x:1},{...n,x:-1}]);const s=g.getState();assert.notEqual(s.players[0].x,s.players[1].x);assert.equal(s.players[1].x,3);});
