import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame} from '../games/jelly.js';
const n={x:0,y:0,action:false,alt:false,pressed:false};
const tick=(g,count,inputs=[n,n])=>{for(let i=0;i<count;i++)g.update(1/30,inputs);};
test('independent movement, dash cooldown, guarding speed and shrinking arena',()=>{const g=createGame({testMode:true});g.__test.skipReady();let s=g.getState();const x=s.players[0].x,r=s.radius;tick(g,12,[{...n,x:1},n]);assert.ok(g.getState().players[0].x>x);assert.equal(g.getState().players[1].x,s.players[1].x);g.update(1/30,[{...n,x:1,pressed:true},n]);assert.ok(g.getState().players[0].cooldown>1);assert.ok(g.getState().radius<r);});
test('collisions transfer actual momentum and guard reduces knockback',()=>{function hit(guard){const g=createGame({testMode:true});g.__test.skipReady();g.__test.setPlayer(0,{x:440,y:305,vx:500,dash:.2});g.__test.setPlayer(1,{x:495,y:305,vx:0});g.update(1/30,[n,{...n,alt:guard}]);return g.getState().players[1].vx;}assert.ok(hit(false)>300);assert.ok(hit(true)<hit(false)*.5);});
test('ringout awards one point, round resets, simultaneous ringout draws',()=>{const g=createGame({testMode:true});g.__test.skipReady();g.__test.setPlayer(0,{x:900,y:305});tick(g,12);assert.equal(g.getState().players[1].score,1);tick(g,35);assert.equal(g.getState().round,2);assert.equal(g.getState().players[1].score,1);const d=createGame({testMode:true});d.__test.skipReady();d.__test.setPlayer(0,{x:0,y:0});d.__test.setPlayer(1,{x:960,y:600});tick(d,12);assert.deepEqual(d.getState().players.map(p=>p.score),[0,0]);});
test('seeded bot games are deterministic, score and terminate once, updates freeze',()=>{let ends=0;function run(onEnd=()=>{}){const g=createGame({seed:17,end:onEnd});let was=[false,false];for(let f=0;f<1900;f++){const ins=[0,1].map(i=>{const v=g.bot(i);v.pressed=v.action&&!was[i];was[i]=v.action;return v;});g.update(1/30,ins);}return g;}const a=run(()=>ends++),b=run();assert.deepEqual(a.getState(),b.getState());assert.equal(ends,1);assert.ok(a.getState().ended);assert.ok(a.getState().players.reduce((s,p)=>s+p.score,0)>0);const snap=a.getState();tick(a,60);assert.deepEqual(a.getState(),snap);});
