import {createGame,WEAPONS} from './engine.js';
import {render} from './renderer.js';
import {Sound} from './sound.js';
const $=id=>document.getElementById(id),canvas=$('range'),ctx=canvas.getContext('2d'),audio=new Sound(),motion=matchMedia('(prefers-reduced-motion: reduce)');
const descriptions={challenge:'抓紧 60 秒，看看你能连中几靶。',practice:'不限时间，慢慢找到瞄准的手感。',duel:'同一设备，两人各 30 秒，使用同一武器与地图种子。'};
const names={challenge:'60秒挑战',practice:'自由练习',duel:'双人轮流对决'};
let mode='challenge',weapon='pistol',game=createGame({mode,weapon,seed:2026}),running=false,paused=false,phase='ready',round=0,rounds=[],duelWeapon='pistol',usedWeapons=new Set(),selectedSeed=2026;
let aim={x:480,y:280},kick=0,lastTime=0,clock=0,accumulator=0,lastHUD=0,nextShotAttempt=0,keyboardTrigger=false,loadBest=0;
const triggerPointers=new Set(),aimPointers=new Map(),fx=[],traces=[];
function setMessage(text){$('status').textContent=text}
function accuracy(s=game.state){return s.shots?Math.round(s.hits/s.shots*100):0}
function safeBest(id){try{const n=Number(localStorage.getItem('sunset-range-best-'+id));return Number.isFinite(n)&&n>=0?n:0}catch{return 0}}
function clearInput(){triggerPointers.clear();aimPointers.clear();keyboardTrigger=false;$('fire').classList.remove('pressed')}
function results(items){$('results').replaceChildren();for(const item of items){const div=document.createElement('div'),label=document.createElement('span'),value=document.createElement('b');label.textContent=item.label;value.textContent=item.value;div.append(label,value);if(item.winner)div.classList.add('winner');$('results').append(div)}$('results').hidden=!items.length}
function overlay(title,copy,cta,kicker='SUNSET RANGE',items=[]){$('overlay').hidden=false;$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('overlay-kicker').textContent=kicker;$('start').textContent=cta+' →';results(items)}
function weaponUI(){document.querySelectorAll('[data-weapon]').forEach(b=>{const id=b.dataset.weapon;b.classList.toggle('selected',id===weapon);b.setAttribute('aria-pressed',String(id===weapon));b.disabled=mode==='duel'&&(running||round>0||phase==='handoff'||phase==='match-end');b.querySelector('b').textContent=WEAPONS[id].name});$('weapon-code').textContent=weapon==='rifle'?'SR.18':'MK.08';loadBest=safeBest(weapon);$('best-score').textContent=loadBest||'—';$('best-score').title=WEAPONS[weapon].name+' · 本机60秒单枪最佳'}
function newGame(){game=createGame({mode,weapon,seed:selectedSeed});accumulator=0;fx.length=0;traces.length=0;kick=0;nextShotAttempt=0;usedWeapons=new Set([weapon]);clearInput();refreshHUD();draw()}
function reset(){running=false;paused=false;phase='ready';round=0;rounds=[];selectedSeed=2026;duelWeapon=weapon;newGame();$('mode-description').textContent=descriptions[mode];$('round-label').textContent=names[mode];$('turn-label').textContent=mode==='duel'?'2 PLAYERS / TAKE TURNS':'SINGLE PLAYER';$('pause').disabled=true;$('pause').textContent='暂停';$('stage').classList.remove('playing');weaponUI();overlay(mode==='duel'?'第一位射手，准备好了吗？':mode==='practice'?'慢一点。每一枪都算数。':'准星就位。轮到你了。',mode==='duel'?'第一位玩家先打 30 秒，再把设备交给第二位。':mode==='practice'?'不限时练习。瞄准、射击，找到自己的节奏。':'移动鼠标瞄准并点击开火。R 换弹，P 暂停。',mode==='duel'?'玩家 1 开始':mode==='practice'?'开始练习':'开始挑战','WELCOME TO THE RANGE');setMessage('靶心 100 分 · 中环 60 分 · 外环 30 分')}
function start(){if(phase==='paused'){togglePause();return}if(phase==='handoff'){round=1;weapon=duelWeapon;newGame()}else if(phase==='ended'||phase==='match-end'){reset()}if(mode==='duel'&&round===0)duelWeapon=weapon;phase='playing';running=true;paused=false;accumulator=0;clearInput();$('overlay').hidden=true;$('stage').classList.add('playing');$('pause').disabled=false;$('pause').textContent='暂停';$('turn-label').textContent=mode==='duel'?'PLAYER '+(round+1)+' / 2':mode==='practice'?'FREE PRACTICE':'SINGLE PLAYER';weaponUI();canvas.focus({preventScroll:true});setMessage(mode==='duel'?'玩家 '+(round+1)+' 的回合 · 30 秒倒计时。':'瞄准靶心。打空或漏靶会中断连击。')}
function togglePause(){if(!running)return;if(!paused){paused=true;phase='paused';clearInput();$('pause').textContent='继续';overlay('先歇一下。准星还在。','靶子和计时已暂停。准备好后继续。','继续射击','PAUSED');setMessage('已暂停，计时、靶子和换弹全部停止。')}else{paused=false;phase='playing';$('overlay').hidden=true;$('pause').textContent='暂停';accumulator=0;canvas.focus({preventScroll:true});setMessage('已继续，找准下一发。')}}
function summary(){const s=game.state;return{score:s.score,shots:s.shots,hits:s.hits,accuracy:accuracy(s),bullseyes:s.bullseyes,bestCombo:s.bestCombo,weapon}}
function finish(){running=false;paused=false;clearInput();$('pause').disabled=true;$('stage').classList.remove('playing');const r=summary();if(mode==='duel'){rounds[round]=r;if(round===0){phase='handoff';overlay('换你了，第二位射手。','第一位已完成。交接期间不计时；同一武器、同一个地图种子，公平开局。','玩家 2 开始','PASS THE DEVICE',[{label:'玩家 1 得分',value:r.score},{label:'命中率',value:r.accuracy+'%'}]);setMessage('回合结束。把设备交给玩家 2，再点开始。')}else{phase='match-end';const a=rounds[0],b=rounds[1],winner=a.score===b.score?'势均力敌，这局平手！':a.score>b.score?'玩家 1，漂亮拿下！':'玩家 2，漂亮拿下！';overlay(winner,'同机轮流对决结束，成绩来自两位玩家的实际射击。','再来一场','MATCH COMPLETE',[{label:'玩家 1',value:a.score,winner:a.score>=b.score},{label:'玩家 2',value:b.score,winner:b.score>=a.score}]);setMessage('两位玩家均已完成 30 秒，最终比分 '+a.score+' : '+b.score+'。')}}else{phase='ended';if(mode==='challenge'&&usedWeapons.size===1){loadBest=safeBest(weapon);if(r.score>loadBest){try{localStorage.setItem('sunset-range-best-'+weapon,String(r.score));loadBest=r.score}catch{}}}const rank=r.score>=5000?'这手准星，稳得漂亮。':r.score>=2000?'连击起来了，手感正好。':'漂亮收工，再来一局？';overlay(rank,'靶心 '+r.bullseyes+' 次 · 最高 '+r.bestCombo+' 连击'+(usedWeapons.size>1?' · 混合武器局不计入单枪最佳':''),'再来一局','ROUND COMPLETE',[{label:'最终得分',value:r.score},{label:'命中率',value:r.accuracy+'%'},{label:'射击次数',value:r.shots}]);setMessage('挑战完成！成绩已按真实射击结算。')}weaponUI();refreshHUD()}
function consume(){for(const e of game.drainEvents()){if(e.type==='shot'){usedWeapons.add(weapon);kick=1;audio.play('shot',weapon);if(!motion.matches){traces.push({x:e.x,y:e.y,life:.075,max:.075});fx.push({kind:'shell',x:722,y:478,vx:135,vy:-140,life:.65,max:.65,size:10,color:'#cead72',rotation:0})}}else if(e.type==='hit'){const bull=e.ring==='bullseye';audio.play(bull?'bullseye':'hit');fx.push({kind:'text',x:e.x,y:e.y-18,vx:0,vy:-26,life:.8,max:.8,text:'+'+e.score,bullseye:bull});fx.push({kind:'hit',x:e.x,y:e.y,life:.2,max:.2,color:bull?'#ffe1a0':'#f7ffe4'});if(!motion.matches)for(let i=0;i<8;i++){const a=i*Math.PI/4;fx.push({kind:'chip',x:e.x,y:e.y,vx:Math.cos(a)*80,vy:Math.sin(a)*70-25,life:.35,max:.35,size:3+i%3,color:i%2?'#f0d6a2':'#b96946'})}setMessage((bull?'命中靶心！':e.ring==='middle'?'中环命中！':'命中外环！')+' +'+e.score+' 分 · '+e.combo+' 连击'+(e.multiplier>1?' · '+e.multiplier+' 倍':''));}else if(e.type==='miss'){audio.play('miss');fx.push({kind:'hit',x:e.x,y:e.y,life:.13,max:.13,color:'#d0907c'});setMessage('这一枪打空了。深呼吸，重新瞄准。')}else if(e.type==='dryfire'){audio.play('dryfire');setMessage('弹匣空了，按 R 或点击“换弹”。')}else if(e.type==='reload'){audio.play('reload');setMessage('正在换弹…')}else if(e.type==='reloaded'){audio.play('reloaded');setMessage('换弹完成，继续射击。')}else if(e.type==='expire'){setMessage('漏掉一靶，连击中断。瞄准下一靶。')}else if(e.type==='end'){audio.play('end');finish()}}}
function shoot(){if(!running||paused||phase!=='playing')return{type:'blocked',reason:'host-paused'};const result=game.shoot(aim.x,aim.y);consume();refreshHUD();return result}
function reload(){if(!running||paused)return false;const changed=game.reload();consume();refreshHUD();return changed}
function chooseWeapon(id){if(!Object.hasOwn(WEAPONS,id)||id===weapon)return;if(mode==='duel'&&(running||round>0||phase==='handoff'||phase==='match-end')){setMessage('双人对决开始后锁定装备，两位玩家使用同一把枪。');return}if(paused)return;weapon=id;if(running){usedWeapons.add(id);game.setWeapon(id);consume()}else newGame();weaponUI();refreshHUD()}
function refreshHUD(){const s=game.state;$('score').textContent=String(s.score).padStart(5,'0');$('combo').innerHTML=s.combo+' <span>COMBO'+(s.multiplier>1?' ×'+s.multiplier:'')+'</span>';$('time').innerHTML=s.timeLeft===null?'∞':Math.ceil(s.timeLeft)+'<span>s</span>';$('time').parentElement.classList.toggle('urgent',s.timeLeft!==null&&s.timeLeft<=10);$('ammo').textContent=String(s.ammo).padStart(2,'0');$('max-ammo').textContent=' / '+String(s.maxAmmo).padStart(2,'0');$('reload-label').textContent=s.reloadRemaining>0?'换弹中 '+s.reloadRemaining.toFixed(1)+'s':s.ammo===0?'按 R 换弹':'READY TO FIRE';$('ammo-meter').innerHTML=Array.from({length:s.maxAmmo},(_,i)=>'<i class="'+(i>=s.ammo?'empty':'')+'"></i>').join('');$('accuracy').textContent=s.shots?accuracy(s)+'%':'—';$('bullseyes').textContent=s.bullseyes;$('best-combo').textContent=s.bestCombo;$('best-score').textContent=loadBest||'—';$('reload').disabled=!running||paused||s.reloadRemaining>0||s.ammo===s.maxAmmo;$('reload-touch').disabled=$('reload').disabled;$('fire').disabled=!running||paused;$('aim-note').textContent=s.reloadRemaining>0?'换弹中，稍等片刻。':weapon==='rifle'?'按住开火可连续射击。':'瞄准红色靶心，拿下 100 分。';$('accessible-state').textContent=names[mode]+'，得分'+s.score+'，子弹'+s.ammo+'，命中率'+accuracy(s)+'%，连击'+s.combo}
function tick(){if(!running||paused)return;game.update(1/120);consume();if(running&&weapon==='rifle'&&(triggerPointers.size||keyboardTrigger)&&game.state.shotCooldown<=0&&clock>=nextShotAttempt){shoot();nextShotAttempt=clock+(game.state.ammo<=0?.2:0)}}
function draw(){const preview=phase==='ready'?{...game.state,targets:game.state.targets.map(t=>({...t,scale:1}))}:game.state;render(ctx,preview,{aim,kick:motion.matches?0:kick,time:clock,fx,traces,reducedMotion:motion.matches,showCrosshair:running&&!paused})}
function frame(now){const dt=lastTime?Math.min(.05,(now-lastTime)/1000):0;lastTime=now;if(!paused)clock+=dt;if(running&&!paused){accumulator+=dt;while(accumulator>=1/120&&running&&!paused){tick();accumulator-=1/120}}if(!paused){kick=Math.max(0,kick-dt*7);for(const arr of[fx,traces])for(let i=arr.length-1;i>=0;i--){const f=arr[i];f.life-=dt;if(f.vx!==undefined){f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.kind!=='text')f.vy+=260*dt;if(f.kind==='shell')f.rotation+=dt*9}if(f.life<=0)arr.splice(i,1)}}if(now-lastHUD>90){refreshHUD();lastHUD=now}draw();requestAnimationFrame(frame)}
function aimAt(e){const r=canvas.getBoundingClientRect();aim.x=Math.max(0,Math.min(960,(e.clientX-r.left)*960/r.width));aim.y=Math.max(0,Math.min(600,(e.clientY-r.top)*600/r.height))}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType==='mouse')return;if(!running||paused)return;e.preventDefault();canvas.focus({preventScroll:true});aimAt(e);canvas.setPointerCapture(e.pointerId);aimPointers.set(e.pointerId,{x:e.clientX,y:e.clientY,moved:false,type:e.pointerType});if(e.pointerType==='mouse'){triggerPointers.add(e.pointerId);shoot()}});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||aimPointers.has(e.pointerId)){aimAt(e);const p=aimPointers.get(e.pointerId);if(p&&Math.hypot(e.clientX-p.x,e.clientY-p.y)>6)p.moved=true}});
for(const event of['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>{const p=aimPointers.get(e.pointerId);if(event==='pointerup'&&p&&p.type!=='mouse'&&!p.moved){aimAt(e);shoot()}triggerPointers.delete(e.pointerId);aimPointers.delete(e.pointerId)});
canvas.addEventListener('contextmenu',e=>e.preventDefault());
$('fire').addEventListener('pointerdown',e=>{if(!running||paused)return;e.preventDefault();$('fire').setPointerCapture(e.pointerId);triggerPointers.add(e.pointerId);$('fire').classList.add('pressed');shoot()});for(const event of['pointerup','pointercancel','lostpointercapture'])$('fire').addEventListener(event,e=>{triggerPointers.delete(e.pointerId);$('fire').classList.toggle('pressed',triggerPointers.size>0)});
$('fire').addEventListener('click',e=>{if(e.detail===0)shoot()});
$('start').addEventListener('click',start);$('pause').addEventListener('click',togglePause);$('restart').addEventListener('click',reset);$('reload').addEventListener('click',reload);$('reload-touch').addEventListener('click',reload);$('mode').addEventListener('change',()=>{mode=$('mode').value;reset()});document.querySelectorAll('[data-weapon]').forEach(b=>b.addEventListener('click',()=>chooseWeapon(b.dataset.weapon)));
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.target.closest?.('input,select,textarea,button,a'))return;if(['Space','KeyR','KeyP','Escape','Digit1','Digit2'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Space'&&running&&!paused){keyboardTrigger=true;shoot()}else if(e.code==='KeyR')reload();else if(e.code==='KeyP'||e.code==='Escape')togglePause();else if(e.code==='Digit1')chooseWeapon('pistol');else if(e.code==='Digit2')chooseWeapon('rifle')});window.addEventListener('keyup',e=>{if(e.code==='Space')keyboardTrigger=false});
window.addEventListener('blur',()=>{clearInput();if(running&&!paused)togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)togglePause();lastTime=0});
$('sound').addEventListener('click',async()=>{try{const on=await audio.toggle();$('sound').textContent='音效 '+(on?'开':'关');$('sound').setAttribute('aria-pressed',String(on));if(on)audio.play('reloaded')}catch{setMessage('当前浏览器无法开启声音，仍可继续游戏。')}});
$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('arena').requestFullscreen()}catch{setMessage('当前浏览器不支持全屏，请使用窗口模式。')}});
window.rangeApp={get game(){return game},get mode(){return mode},get weapon(){return weapon},get running(){return running},get paused(){return paused},get phase(){return phase},get round(){return round},get rounds(){return structuredClone(rounds)},get aim(){return {...aim}},get triggerHeld(){return keyboardTrigger||triggerPointers.size>0},get sound(){return{enabled:audio.enabled,state:audio.ctx?.state||'uncreated'}},start,reset,pause:togglePause,reload,chooseWeapon,shoot,step(n=1){for(let i=0;i<n&&running&&!paused;i++)tick();refreshHUD();draw();return game.state}};
reset();requestAnimationFrame(frame);
