import {createGame,LEVELS} from './engine.js';
import {render} from './renderer.js';
import {Sound} from './sound.js';

const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),sound=new Sound();
const keys={left:false,right:false,jump:false,run:false},pointers=new Map(),effects=[];
const actions={left:'向左移动',right:'向右移动',jump_left:'向左跳跃',jump_right:'向右跳跃',wait:'等待'};
let game=createGame(0),levelIndex=0,mode='human',running=false,paused=false,overlayAction='start',last=0,accumulator=0,clock=0,lastUI=0;
let aiState={state:'unloaded'},aiAction='wait',aiPending=false,aiGeneration=0,aiController=null,aiRequest=null,aiNext=0,decisionCount=0,jumpPhase=0,loadPromise=null;
const motion=matchMedia('(prefers-reduced-motion: reduce)');
const modeNames={human:'手动闯关',bot:'规则机器人演示',laya:'Laya 实验控制'};
const descriptions={human:'方向、起跳和节奏，都由你掌握。',bot:'规则机器人实际闯关，适合先熟悉地图。',laya:'本地模型实验控制，尚未针对本游戏训练，可能等待或失误。'};
function message(text){$('game-message').textContent=text}
function clearInputs(){downKeys.clear();for(const k in keys)keys[k]=false;pointers.clear();document.querySelectorAll('[data-input]').forEach(b=>b.classList.remove('pressed'))}
function cancelAI(){aiGeneration++;aiController?.abort();if(aiRequest)fetch('/api/ai/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:aiRequest})}).catch(()=>{});aiController=null;aiRequest=null;aiPending=false;aiAction='wait';jumpPhase=0}
function overlay(title,copy,label,action,kicker='CLOUD COURIER'){$('overlay').hidden=false;$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('start').innerHTML=label+' <span aria-hidden="true">→</span>';$('start').disabled=false;$('overlay-kicker').textContent=kicker;overlayAction=action}
function levelLabel(){return LEVELS[levelIndex].name.replace(/^\d+\s*[·/]\s*/,'')}
function syncMode(){mode=$('mode').value;$('mode-badge').textContent=modeNames[mode];$('mode-help').textContent=descriptions[mode]}
function reset(){cancelAI();clearInputs();game=createGame(levelIndex);effects.length=0;running=false;paused=false;accumulator=0;decisionCount=0;$('decision-count').textContent='0';$('latency').innerHTML='—<small> ms</small>';$('decision-action').textContent='等待开局';$('confidence-bar').style.width='0';$('pause').disabled=true;$('pause').textContent='暂停';$('viewport').classList.toggle('night',levelIndex===2);$('world-title').textContent=String(levelIndex+1).padStart(2,'0')+' / '+levelLabel();document.querySelectorAll('[data-level]').forEach(b=>{const selected=Number(b.dataset.level)===levelIndex;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected))});overlay(levelIndex===0?'今天，往高处走。':levelIndex===1?'下一站，晚风正好。':'最后一程，追上星光。',mode==='human'?'方向键移动 · 空格跳跃，长按跳得更高。':mode==='bot'?'规则机器人将按真实物理与规则自动闯关。':'本地模型每次读取当前场景，决定下一个动作。','开始冒险','start','READY FOR TAKEOFF');message(mode==='human'?'准备好，第一站就在云层上面。':descriptions[mode]);refreshHUD();draw()}
function selectLevel(index){levelIndex=Math.max(0,Math.min(2,index));reset()}
function refreshHUD(){const s=game.state,p=s.player;$('hearts').textContent='♥ '.repeat(p.hp)+'♡ '.repeat(Math.max(0,3-p.hp));$('coins').textContent=String(s.coins).padStart(3,'0');$('score').textContent=String(s.score).padStart(5,'0');const sec=Math.floor(s.elapsed);$('clock').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');$('accessible-state').textContent=levelLabel()+'，生命'+p.hp+'，金币'+s.coins+'，得分'+s.score+'，'+modeNames[mode]}
function onEvent(e){sound.play(e.type);const colors=['#ffe194','#f6f2cc','#e69457'];if(!motion.matches&&['coin','stomp','checkpoint','win','hurt','jump'].includes(e.type)){for(let i=0;i<(e.type==='win'?28:6);i++){const a=i*2.399;effects.push({x:e.x,y:e.y,vx:Math.cos(a)*65,vy:-45-Math.sin(a)*50,life:.45,max:.45,size:3+i%3,color:colors[i%3]})}}if(e.type==='coin'||e.type==='stomp')effects.push({x:e.x,y:e.y-14,vx:0,vy:-30,life:.8,max:.8,text:e.type==='coin'?'+100':'+200'});if(e.type==='checkpoint')message('中途站已点亮，失误后从这里继续。');if(e.type==='hurt')message('小心！从上方落下才能踩住小怪。');if(e.type==='death')message(game.state.player.hp?'跌下山谷，回到最近的投递站。':'先歇一下，再试一次。');}
function finish(){running=false;paused=false;clearInputs();cancelAI();$('pause').disabled=true;const s=game.state;if(s.status==='won'){const lastLevel=levelIndex===2;overlay(lastLevel?'每一份勇气，都送到了。':'这一站，漂亮抵达！','收集 '+s.coins+' 枚金币 · '+s.score+' 分 · '+s.elapsed.toFixed(1)+' 秒',lastLevel?'重新冒险':'前往下一站',lastLevel?'again':'next','DELIVERY COMPLETE');message(modeNames[mode]+' · 本关完成，分数来自真实游戏规则。')}else{overlay('再跳一次，就会更远。','这一路已经收获 '+s.coins+' 枚金币。重新整理背包，再来一次。','再试一次','reset','TAKE A BREATH');message('生命用完了。本关可以重新挑战。')}refreshHUD()}
function tick(input){game.update(1/120,input);for(const e of game.state.events)onEvent(e);if(game.state.status!=='playing')finish()}
function aiInput(dt){const jumping=aiAction==='jump_left'||aiAction==='jump_right';if(jumping)jumpPhase=(jumpPhase+dt)%.28;else jumpPhase=0;return{left:aiAction==='left'||aiAction==='jump_left',right:aiAction==='right'||aiAction==='jump_right',jump:jumping&&jumpPhase<.18,run:false}}
function draw(){render(ctx,game.state,{levelIndex,fx:effects,time:clock,reducedMotion:motion.matches})}
function frame(now){const delta=last?Math.min(.05,(now-last)/1000):0;last=now;if(!paused)clock+=delta;if(running&&!paused){accumulator+=delta;while(accumulator>=1/120&&running&&!paused){const input=mode==='human'?keys:mode==='bot'?game.getBotInput():aiInput(1/120);tick(input);accumulator-=1/120}if(mode==='laya'&&now>=aiNext&&!aiPending)decide();}for(let i=effects.length-1;i>=0;i--){const f=effects[i];f.life-=delta;f.x+=f.vx*delta;f.y+=f.vy*delta;if(!f.text)f.vy+=110*delta;if(f.life<=0)effects.splice(i,1)}if(now-lastUI>100){refreshHUD();lastUI=now}draw();requestAnimationFrame(frame)}
async function request(path,body,signal){const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?undefined:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal});let data;try{data=await res.json()}catch{throw Error('本地服务没有返回有效数据')}if(!res.ok){const error=Error(data.error||data.message||'本地请求失败');error.status=res.status;throw error}return data}
function showAIStatus(data){aiState=data;const text={unloaded:'本地权重可用，按需加载。',loading:'首次加载可能需要数分钟，请稍候…',ready:'本地模型已就绪 · '+(data.device||'CPU'),error:data.error||'模型暂不可用'};$('ai-status').textContent=data.available===false?(data.error||'未找到本地模型，手动和规则演示仍可使用。'):(text[data.state]||'正在检查本地模型…');$('load-ai').disabled=data.state==='loading'||data.state==='ready';$('load-ai').textContent=data.state==='ready'?'本地模型已就绪':data.state==='loading'?'正在加载…':'加载本地 Laya'}
async function checkAI(){try{const status=await request('/api/ai/status',undefined,AbortSignal.timeout(4000));showAIStatus(status);if(status.state==='loading'&&!loadPromise)setTimeout(checkAI,1000)}catch(e){showAIStatus({state:'error',available:false,error:'请通过启动脚本打开游戏，才能使用本地模型。'})}}
async function loadAI(){if(aiState.state==='ready')return;if(loadPromise)return loadPromise;loadPromise=(async()=>{showAIStatus({...aiState,state:'loading'});try{await request('/api/ai/load',{},AbortSignal.timeout(15000));for(let i=0;i<375;i++){const state=await request('/api/ai/status',undefined,AbortSignal.timeout(6000));showAIStatus(state);if(state.state==='ready')return;if(state.state==='error')throw Error(state.error||'模型加载失败');await new Promise(resolve=>setTimeout(resolve,800))}throw Error('模型加载超过五分钟，请检查服务终端。')}catch(e){showAIStatus({state:'error',available:false,error:e.message});throw e}finally{loadPromise=null}})();return loadPromise}
async function start(requestedMode){if(requestedMode&&requestedMode!==mode){$('mode').value=requestedMode;syncMode();reset()}const generation=aiGeneration;if(mode==='laya'){try{$('start').disabled=true;$('start').textContent='加载本地模型…';await loadAI();if(generation!==aiGeneration)return}catch(e){if(generation!==aiGeneration)return;overlay('模型暂时没有准备好。',e.message,'重试加载','start','LOCAL MODEL');message('Laya 未开始：'+e.message);return}}running=true;paused=false;overlayAction='start';$('overlay').hidden=true;$('pause').disabled=false;$('pause').textContent='暂停';aiNext=0;accumulator=0;clearInputs();canvas.focus({preventScroll:true});message(mode==='human'?'向右出发！空格起跳，Shift 加速。':mode==='bot'?'规则机器人正在演示 · 非模型推理。':'Laya 正在读取场景，实时决定动作。')}
function pause(){if(!running)return;paused=!paused;clearInputs();cancelAI();accumulator=0;$('pause').textContent=paused?'继续':'暂停';if(paused){overlay('把冒险，暂停一下。','准备好了，就继续往前走。','继续冒险','resume','PAUSED');message('已暂停，游戏时间与人物停止。')}else{$('overlay').hidden=true;aiNext=0;canvas.focus({preventScroll:true});message(modeNames[mode]+' · 已继续。')}}
async function decide(){if(mode!=='laya'||!running||paused||aiPending)return;const generation=aiGeneration;aiPending=true;const requestId='game-'+generation+'-'+Date.now()+'-'+decisionCount;aiRequest=requestId;const controller=new AbortController();aiController=controller;const timeout=setTimeout(()=>controller.abort(),14000);try{const r=await request('/api/ai/decision',{observation:game.observation(),requestId,timeoutMs:12000},aiController.signal);if(generation!==aiGeneration||paused||!running)return;if(r.measured!==true||!Object.hasOwn(actions,r.action)||!Number.isFinite(r.latencyMs))throw Error('模型响应缺少真实决策字段');aiAction=r.action;decisionCount++;$('latency').innerHTML=r.latencyMs.toFixed(1)+'<small> ms</small>';$('decision-count').textContent=decisionCount;$('decision-action').textContent=actions[r.action];const conf=Number(r.confidence);$('confidence-bar').style.width=(Number.isFinite(conf)?Math.min(100,Math.max(0,conf*100)):0)+'%';$('ai-note').textContent='模型：'+r.model+' · '+(r.device||'CPU')+' · 置信度 '+(Number.isFinite(conf)?(conf*100).toFixed(1)+'%':'未返回');aiNext=performance.now()+45;}catch(e){if(generation!==aiGeneration)return;if(e.status===429){aiNext=performance.now()+350;aiAction='wait';message('模型仍在处理上一条请求，角色等待下一次真实决策。')}else{paused=true;clearInputs();aiAction='wait';$('pause').textContent='继续';overlay('Laya 暂时停下了。',e.name==='AbortError'?'本次推理超时，可重试或切换手动闯关。':e.message,'重试模型闯关','retry','MODEL REQUEST PAUSED');message('模型请求失败，游戏已暂停；未使用规则机器人替代。');}}finally{clearTimeout(timeout);if(generation===aiGeneration){aiPending=false;aiRequest=null;aiController=null}}}
$('start').addEventListener('click',()=>{if(overlayAction==='resume')pause();else if(overlayAction==='next'){selectLevel(levelIndex+1);start()}else if(overlayAction==='again'){selectLevel(0);start()}else if(overlayAction==='reset'){reset();start()}else if(overlayAction==='retry'){cancelAI();start()}else start()});$('pause').addEventListener('click',pause);$('restart').addEventListener('click',reset);$('mode').addEventListener('change',()=>{syncMode();reset()});document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>selectLevel(Number(b.dataset.level))));
$('load-ai').addEventListener('click',()=>loadAI().catch(e=>message('模型加载失败：'+e.message)));$('sound').addEventListener('click',async()=>{try{const on=await sound.toggle();$('sound').textContent='声音 '+(on?'开':'关');$('sound').setAttribute('aria-pressed',String(on));if(on)sound.play('coin')}catch{message('当前浏览器未能启用声音。')}});$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game-area').requestFullscreen()}catch{message('当前浏览器暂不支持全屏，可使用窗口模式。')}});
const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump',ShiftLeft:'run',ShiftRight:'run'};const downKeys=new Set();function syncKeys(){for(const key of Object.keys(keys))keys[key]=[...downKeys].some(code=>keyMap[code]===key)||[...pointers.values()].includes(key)}
window.addEventListener('keydown',e=>{if(e.target.closest?.('input,textarea,select,button,a'))return;if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='KeyP'||e.code==='Escape'){if(!e.repeat)pause();return}if(keyMap[e.code]&&mode==='human'&&running&&!paused){e.preventDefault();downKeys.add(e.code);syncKeys()}});window.addEventListener('keyup',e=>{if(keyMap[e.code]){downKeys.delete(e.code);syncKeys()}});
document.querySelectorAll('[data-input]').forEach(b=>{b.addEventListener('pointerdown',e=>{if(mode!=='human'||!running||paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.input);b.classList.add('pressed');syncKeys()});for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{pointers.delete(e.pointerId);b.classList.toggle('pressed',[...pointers.values()].includes(b.dataset.input));syncKeys()})});
window.addEventListener('blur',()=>{downKeys.clear();clearInputs();if(running&&!paused)pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)pause();last=0});
document.querySelectorAll('[data-level]').forEach((b,i)=>{b.querySelector('b').textContent=LEVELS[i].name.replace(/^\d+\s*[·/]\s*/,'')});
window.arcade={get game(){return game},get mode(){return mode},get running(){return running},get paused(){return paused},get aiState(){return aiState},get decisionCount(){return decisionCount},start,pause,reset,selectLevel,step(n=1,input){for(let i=0;i<n;i++){tick(input||game.getBotInput());if(game.state.status!=='playing')break}refreshHUD();draw();return game.state},get input(){return {...keys}},render:draw};
syncMode();reset();checkAI();requestAnimationFrame(frame);
